name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . -t khm0930/cloud_storage_web:${{ github.sha }}

    - name: Push the Docker image to Docker Hub
      run: docker push khm0930/cloud_storage_web:${{ github.sha }}
    
    - name: Set latest tag on Docker Hub
      run: docker tag khm0930/cloud_storage_web:${{ github.sha }} khm0930/cloud_storage_web:latest

    - name: Push latest tag to Docker Hub
      run: docker push khm0930/cloud_storage_web:latest
